
spring:
  cloud:
    gateway:
      routes:
        - id: country
          uri: http://localhost:8081
          predicates:
            - Path=/country,/org/v1/country
          filters:
            - AddRequestHeader=X-gateway-screened, true
            - AddResponseHeader=X-gateway-screened, true
            - SetPath=/org/v1/country
      metrics:
        enabled: true

server:
  port: 8080

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
