
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: country
          uri: lb://service-countries
          predicates:
            - Path=/country,/org/v1/country
          filters:
            - AddRequestHeader=X-gateway-screened, true
            - AddResponseHeader=X-gateway-screened, true
            - SetPath=/org/v1/country
        - id: hello_service_tobe
          uri: http://localhost:8081
          predicates:
            - Path=/migration/hello
            - Weight=hello_service, 1
          filters:
            - SetPath=/new/hello
        - id: hello_service_current
          uri: http://localhost:8081
          predicates:
            - Path=/migration/hello
            - Weight=hello_service, 9
          filters:
            - SetPath=/old/hello
      metrics:
        enabled: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

# For deep troubleshooting keep these loggers are DEBUG/TRACE Level
# Refer: https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#log-levels
logging:
  level:
    root: INFO
    org:
      springframework:
        http.server.reactive: INFO
        cloud.gateway: INFO
        web.reactive: INFO
        boot.autoconfigure.web: INFO
    reactor.netty: INFO
    redisratelimiter: INFO
