
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: country
          uri: lb://service-countries
          predicates:
            - Path=/country,/org/v1/country
          filters:
            - AddRequestHeader=X-gateway-screened, true
            - AddResponseHeader=X-gateway-screened, true
            - SetPath=/org/v1/country
      metrics:
        enabled: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
