package edu.san.servercountry.repo;

import static java.util.Map.entry;

import edu.san.servercountry.models.Country;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.stereotype.Repository;

@Repository
public class CountryRepository {

  private final Map<String, Country> countries = generateData();

  public List<Country> getAll() {
    return new ArrayList<>(countries.values());
  }

  public Optional<Country> getCountryByCode(String code) {
    return Optional.ofNullable(countries.get(code));
  }



  private static Map<String, Country> generateData() {
    return Map.ofEntries(
        entry("AFG", new Country ("Afghanistan","AFG")),
        entry("ALA", new Country ("Aland Islands","ALA")),
        entry("ALB", new Country ("Albania","ALB")),
        entry("DZA", new Country ("Algeria","DZA")),
        entry("ASM", new Country ("American Samoa","ASM")),
        entry("AND", new Country ("Andorra","AND")),
        entry("AGO", new Country ("Angola","AGO")),
        entry("AIA", new Country ("Anguilla","AIA")),
        entry("ATA", new Country ("Antarctica","ATA")),
        entry("ATG", new Country ("Antigua and Barbuda","ATG")),
        entry("ARG", new Country ("Argentina","ARG")),
        entry("ARM", new Country ("Armenia","ARM")),
        entry("ABW", new Country ("Aruba","ABW")),
        entry("AUS", new Country ("Australia","AUS")),
        entry("AUT", new Country ("Austria","AUT")),
        entry("AZE", new Country ("Azerbaijan","AZE")),
        entry("BHS", new Country ("Bahamas","BHS")),
        entry("BHR", new Country ("Bahrain","BHR")),
        entry("BGD", new Country ("Bangladesh","BGD")),
        entry("BRB", new Country ("Barbados","BRB")),
        entry("BLR", new Country ("Belarus","BLR")),
        entry("BEL", new Country ("Belgium","BEL")),
        entry("BLZ", new Country ("Belize","BLZ")),
        entry("BEN", new Country ("Benin","BEN")),
        entry("BMU", new Country ("Bermuda","BMU")),
        entry("BTN", new Country ("Bhutan","BTN")),
        entry("BOL", new Country ("Bolivia","BOL")),
        entry("BIH", new Country ("Bosnia and Herzegovina","BIH")),
        entry("BWA", new Country ("Botswana","BWA")),
        entry("BVT", new Country ("Bouvet Island","BVT")),
        entry("BRA", new Country ("Brazil","BRA")),
        entry("VGB", new Country ("British Virgin Islands","VGB")),
        entry("IOT", new Country ("British Indian Ocean Territory","IOT")),
        entry("BRN", new Country ("Brunei Darussalam","BRN")),
        entry("BGR", new Country ("Bulgaria","BGR")),
        entry("BFA", new Country ("Burkina Faso","BFA")),
        entry("BDI", new Country ("Burundi","BDI")),
        entry("KHM", new Country ("Cambodia","KHM")),
        entry("CMR", new Country ("Cameroon","CMR")),
        entry("CAN", new Country ("Canada","CAN")),
        entry("CPV", new Country ("Cape Verde","CPV")),
        entry("CYM", new Country ("Cayman Islands","CYM")),
        entry("CAF", new Country ("Central African Republic","CAF")),
        entry("TCD", new Country ("Chad","TCD")),
        entry("CHL", new Country ("Chile","CHL")),
        entry("CHN", new Country ("China","CHN")),
        entry("HKG", new Country ("Hong Kong, SAR China","HKG")),
        entry("MAC", new Country ("Macao, SAR China","MAC")),
        entry("CXR", new Country ("Christmas Island","CXR")),
        entry("CCK", new Country ("Cocos (Keeling) Islands","CCK")),
        entry("COL", new Country ("Colombia","COL")),
        entry("COM", new Country ("Comoros","COM")),
        entry("COG", new Country ("Congo (Brazzaville)","COG")),
        entry("COD", new Country ("Congo, (Kinshasa)","COD")),
        entry("COK", new Country ("Cook Islands","COK")),
        entry("CRI", new Country ("Costa Rica","CRI")),
        entry("CIV", new Country ("Côte d'Ivoire","CIV")),
        entry("HRV", new Country ("Croatia","HRV")),
        entry("CUB", new Country ("Cuba","CUB")),
        entry("CYP", new Country ("Cyprus","CYP")),
        entry("CZE", new Country ("Czech Republic","CZE")),
        entry("DNK", new Country ("Denmark","DNK")),
        entry("DJI", new Country ("Djibouti","DJI")),
        entry("DMA", new Country ("Dominica","DMA")),
        entry("DOM", new Country ("Dominican Republic","DOM")),
        entry("ECU", new Country ("Ecuador","ECU")),
        entry("EGY", new Country ("Egypt","EGY")),
        entry("SLV", new Country ("El Salvador","SLV")),
        entry("GNQ", new Country ("Equatorial Guinea","GNQ")),
        entry("ERI", new Country ("Eritrea","ERI")),
        entry("EST", new Country ("Estonia","EST")),
        entry("ETH", new Country ("Ethiopia","ETH")),
        entry("FLK", new Country ("Falkland Islands (Malvinas)","FLK")),
        entry("FRO", new Country ("Faroe Islands","FRO")),
        entry("FJI", new Country ("Fiji","FJI")),
        entry("FIN", new Country ("Finland","FIN")),
        entry("FRA", new Country ("France","FRA")),
        entry("GUF", new Country ("French Guiana","GUF")),
        entry("PYF", new Country ("French Polynesia","PYF")),
        entry("ATF", new Country ("French Southern Territories","ATF")),
        entry("GAB", new Country ("Gabon","GAB")),
        entry("GMB", new Country ("Gambia","GMB")),
        entry("GEO", new Country ("Georgia","GEO")),
        entry("DEU", new Country ("Germany","DEU")),
        entry("GHA", new Country ("Ghana","GHA")),
        entry("GIB", new Country ("Gibraltar","GIB")),
        entry("GRC", new Country ("Greece","GRC")),
        entry("GRL", new Country ("Greenland","GRL")),
        entry("GRD", new Country ("Grenada","GRD")),
        entry("GLP", new Country ("Guadeloupe","GLP")),
        entry("GUM", new Country ("Guam","GUM")),
        entry("GTM", new Country ("Guatemala","GTM")),
        entry("GGY", new Country ("Guernsey","GGY")),
        entry("GIN", new Country ("Guinea","GIN")),
        entry("GNB", new Country ("Guinea-Bissau","GNB")),
        entry("GUY", new Country ("Guyana","GUY")),
        entry("HTI", new Country ("Haiti","HTI")),
        entry("HMD", new Country ("Heard and Mcdonald Islands","HMD")),
        entry("VAT", new Country ("Holy See (Vatican City State)","VAT")),
        entry("HND", new Country ("Honduras","HND")),
        entry("HUN", new Country ("Hungary","HUN")),
        entry("ISL", new Country ("Iceland","ISL")),
        entry("IND", new Country ("India","IND")),
        entry("IDN", new Country ("Indonesia","IDN")),
        entry("IRN", new Country ("Iran, Islamic Republic of","IRN")),
        entry("IRQ", new Country ("Iraq","IRQ")),
        entry("IRL", new Country ("Ireland","IRL")),
        entry("IMN", new Country ("Isle of Man","IMN")),
        entry("ISR", new Country ("Israel","ISR")),
        entry("ITA", new Country ("Italy","ITA")),
        entry("JAM", new Country ("Jamaica","JAM")),
        entry("JPN", new Country ("Japan","JPN")),
        entry("JEY", new Country ("Jersey","JEY")),
        entry("JOR", new Country ("Jordan","JOR")),
        entry("KAZ", new Country ("Kazakhstan","KAZ")),
        entry("KEN", new Country ("Kenya","KEN")),
        entry("KIR", new Country ("Kiribati","KIR")),
        entry("PRK", new Country ("Korea (North)","PRK")),
        entry("KOR", new Country ("Korea (South)","KOR")),
        entry("KWT", new Country ("Kuwait","KWT")),
        entry("KGZ", new Country ("Kyrgyzstan","KGZ")),
        entry("LAO", new Country ("Lao PDR","LAO")),
        entry("LVA", new Country ("Latvia","LVA")),
        entry("LBN", new Country ("Lebanon","LBN")),
        entry("LSO", new Country ("Lesotho","LSO")),
        entry("LBR", new Country ("Liberia","LBR")),
        entry("LBY", new Country ("Libya","LBY")),
        entry("LIE", new Country ("Liechtenstein","LIE")),
        entry("LTU", new Country ("Lithuania","LTU")),
        entry("LUX", new Country ("Luxembourg","LUX")),
        entry("MKD", new Country ("Macedonia, Republic of","MKD")),
        entry("MDG", new Country ("Madagascar","MDG")),
        entry("MWI", new Country ("Malawi","MWI")),
        entry("MYS", new Country ("Malaysia","MYS")),
        entry("MDV", new Country ("Maldives","MDV")),
        entry("MLI", new Country ("Mali","MLI")),
        entry("MLT", new Country ("Malta","MLT")),
        entry("MHL", new Country ("Marshall Islands","MHL")),
        entry("MTQ", new Country ("Martinique","MTQ")),
        entry("MRT", new Country ("Mauritania","MRT")),
        entry("MUS", new Country ("Mauritius","MUS")),
        entry("MYT", new Country ("Mayotte","MYT")),
        entry("MEX", new Country ("Mexico","MEX")),
        entry("FSM", new Country ("Micronesia, Federated States of","FSM")),
        entry("MDA", new Country ("Moldova","MDA")),
        entry("MCO", new Country ("Monaco","MCO")),
        entry("MNG", new Country ("Mongolia","MNG")),
        entry("MNE", new Country ("Montenegro","MNE")),
        entry("MSR", new Country ("Montserrat","MSR")),
        entry("MAR", new Country ("Morocco","MAR")),
        entry("MOZ", new Country ("Mozambique","MOZ")),
        entry("MMR", new Country ("Myanmar","MMR")),
        entry("NAM", new Country ("Namibia","NAM")),
        entry("NRU", new Country ("Nauru","NRU")),
        entry("NPL", new Country ("Nepal","NPL")),
        entry("NLD", new Country ("Netherlands","NLD")),
        entry("ANT", new Country ("Netherlands Antilles","ANT")),
        entry("NCL", new Country ("New Caledonia","NCL")),
        entry("NZL", new Country ("New Zealand","NZL")),
        entry("NIC", new Country ("Nicaragua","NIC")),
        entry("NER", new Country ("Niger","NER")),
        entry("NGA", new Country ("Nigeria","NGA")),
        entry("NIU", new Country ("Niue","NIU")),
        entry("NFK", new Country ("Norfolk Island","NFK")),
        entry("MNP", new Country ("Northern Mariana Islands","MNP")),
        entry("NOR", new Country ("Norway","NOR")),
        entry("OMN", new Country ("Oman","OMN")),
        entry("PAK", new Country ("Pakistan","PAK")),
        entry("PLW", new Country ("Palau","PLW")),
        entry("PSE", new Country ("Palestinian Territory","PSE")),
        entry("PAN", new Country ("Panama","PAN")),
        entry("PNG", new Country ("Papua New Guinea","PNG")),
        entry("PRY", new Country ("Paraguay","PRY")),
        entry("PER", new Country ("Peru","PER")),
        entry("PHL", new Country ("Philippines","PHL")),
        entry("PCN", new Country ("Pitcairn","PCN")),
        entry("POL", new Country ("Poland","POL")),
        entry("PRT", new Country ("Portugal","PRT")),
        entry("PRI", new Country ("Puerto Rico","PRI")),
        entry("QAT", new Country ("Qatar","QAT")),
        entry("REU", new Country ("Réunion","REU")),
        entry("ROU", new Country ("Romania","ROU")),
        entry("RUS", new Country ("Russian Federation","RUS")),
        entry("RWA", new Country ("Rwanda","RWA")),
        entry("BLM", new Country ("Saint-Barthélemy","BLM")),
        entry("SHN", new Country ("Saint Helena","SHN")),
        entry("KNA", new Country ("Saint Kitts and Nevis","KNA")),
        entry("LCA", new Country ("Saint Lucia","LCA")),
        entry("MAF", new Country ("Saint-Martin (French part)","MAF")),
        entry("SPM", new Country ("Saint Pierre and Miquelon","SPM")),
        entry("VCT", new Country ("Saint Vincent and Grenadines","VCT")),
        entry("WSM", new Country ("Samoa","WSM")),
        entry("SMR", new Country ("San Marino","SMR")),
        entry("STP", new Country ("Sao Tome and Principe","STP")),
        entry("SAU", new Country ("Saudi Arabia","SAU")),
        entry("SEN", new Country ("Senegal","SEN")),
        entry("SRB", new Country ("Serbia","SRB")),
        entry("SYC", new Country ("Seychelles","SYC")),
        entry("SLE", new Country ("Sierra Leone","SLE")),
        entry("SGP", new Country ("Singapore","SGP")),
        entry("SVK", new Country ("Slovakia","SVK")),
        entry("SVN", new Country ("Slovenia","SVN")),
        entry("SLB", new Country ("Solomon Islands","SLB")),
        entry("SOM", new Country ("Somalia","SOM")),
        entry("ZAF", new Country ("South Africa","ZAF")),
        entry("SGS", new Country ("South Georgia and the South Sandwich Islands","SGS")),
        entry("SSD", new Country ("South Sudan","SSD")),
        entry("ESP", new Country ("Spain","ESP")),
        entry("LKA", new Country ("Sri Lanka","LKA")),
        entry("SDN", new Country ("Sudan","SDN")),
        entry("SUR", new Country ("Suriname","SUR")),
        entry("SJM", new Country ("Svalbard and Jan Mayen Islands","SJM")),
        entry("SWZ", new Country ("Swaziland","SWZ")),
        entry("SWE", new Country ("Sweden","SWE")),
        entry("CHE", new Country ("Switzerland","CHE")),
        entry("SYR", new Country ("Syrian Arab Republic (Syria)","SYR")),
        entry("TWN", new Country ("Taiwan, Republic of China","TWN")),
        entry("TJK", new Country ("Tajikistan","TJK")),
        entry("TZA", new Country ("Tanzania, United Republic of","TZA")),
        entry("THA", new Country ("Thailand","THA")),
        entry("TLS", new Country ("Timor-Leste","TLS")),
        entry("TGO", new Country ("Togo","TGO")),
        entry("TKL", new Country ("Tokelau","TKL")),
        entry("TON", new Country ("Tonga","TON")),
        entry("TTO", new Country ("Trinidad and Tobago","TTO")),
        entry("TUN", new Country ("Tunisia","TUN")),
        entry("TUR", new Country ("Turkey","TUR")),
        entry("TKM", new Country ("Turkmenistan","TKM")),
        entry("TCA", new Country ("Turks and Caicos Islands","TCA")),
        entry("TUV", new Country ("Tuvalu","TUV")),
        entry("UGA", new Country ("Uganda","UGA")),
        entry("UKR", new Country ("Ukraine","UKR")),
        entry("ARE", new Country ("United Arab Emirates","ARE")),
        entry("GBR", new Country ("United Kingdom","GBR")),
        entry("USA", new Country ("United States of America","USA")),
        entry("UMI", new Country ("US Minor Outlying Islands","UMI")),
        entry("URY", new Country ("Uruguay","URY")),
        entry("UZB", new Country ("Uzbekistan","UZB")),
        entry("VUT", new Country ("Vanuatu","VUT")),
        entry("VEN", new Country ("Venezuela (Bolivarian Republic)","VEN")),
        entry("VNM", new Country ("Viet Nam","VNM")),
        entry("VIR", new Country ("Virgin Islands, US","VIR")),
        entry("WLF", new Country ("Wallis and Futuna Islands","WLF")),
        entry("ESH", new Country ("Western Sahara","ESH")),
        entry("YEM", new Country ("Yemen","YEM")),
        entry("ZMB", new Country ("Zambia","ZMB")),
        entry("ZWE", new Country ("Zimbabwe","ZWE"))
    );
  }

}
